
    CREATE TABLE staging.export_patron_data (
    patron_id VARCHAR(5) NOT NULL,
patron_type VARCHAR(23) NOT NULL,
salutation VARCHAR(11) NULL,
first_name VARCHAR(31) NULL,
initial VARCHAR(22) NULL,
last_name VARCHAR(22) NULL,
suffix INT NULL,
greeting VARCHAR(20) NULL,
formal_name VARCHAR(44) NULL,
company VARCHAR(255) NULL,
title VARCHAR(29) NULL,
deceased BIT NULL,
gender VARCHAR(7) NULL,
birthday VARCHAR(10) NULL,
anniversary VARCHAR(10) NULL,
donation_publication_name VARCHAR(39) NULL,
do_not_mail_patron BIT NULL,
do_not_mail_venue BIT NULL,
do_not_email BIT NULL,
do_not_telemarket BIT NULL,
do_not_trade BIT NULL,
do_not_solicit_email BIT NULL,
do_not_solicit_mail BIT NULL,
do_not_solicit_phone BIT NULL,
employee_must_read_notes BIT NULL,
mktg_age_code VARCHAR(5) NULL,
mktg_volunteer VARCHAR(21) NULL,
notes_household VARCHAR(255) NULL,
special_needs_notes VARCHAR(19) NULL,
notes_patron_general_notes VARCHAR(1000) NULL,
notes_donor VARCHAR(255) NULL,
notes_medical_behaviour VARCHAR(255) NULL,
notes_note_3 VARCHAR(1000) NULL,
notes_note_4 VARCHAR(38) NULL,
address_line_1 VARCHAR(50) NULL,
address_line_2 VARCHAR(30) NULL,
city VARCHAR(30) NULL,
province VARCHAR(11) NULL,
postal_code VARCHAR(10) NULL,
country VARCHAR(9) NULL,
primary_phone VARCHAR(23) NULL,
primary_email VARCHAR(47) NULL,
primary_web VARCHAR(26) NULL,
match_gift_company BIT NULL,
match_gift_ratio INT NULL,
match_gift_amount_minimum INT NULL,
match_gift_amount_maximum INT NULL,
primary_address INT NULL,
primary_phone_2 INT NULL,
primary_fax INT NULL,
primary_email_2 INT NULL,
primary_web_2 INT NULL,
household_id INT NULL,
primary_household_patron_id INT NULL,
created_at DATETIME DEFAULT GETDATE()
    );
    