
    CREATE TABLE staging.export_ticket_event_performances (
    event_id VARCHAR(4) NOT NULL,
year VARCHAR(4) NOT NULL,
event_code VARCHAR(6) NOT NULL,
event_title VARCHAR(255) NOT NULL,
event_total_sold VARCHAR(4) NOT NULL,
event_total_held VARCHAR(4) NOT NULL,
sales_notes_internal VARCHAR(1000) NULL,
sales_notes_external VARCHAR(MAX) NULL,
performance_id VARCHAR(4) NOT NULL,
performance_code VARCHAR(8) NOT NULL,
date VARCHAR(10) NOT NULL,
time VARCHAR(8) NOT NULL,
sales_method VARCHAR(17) NOT NULL,
total_sold VARCHAR(4) NOT NULL,
total_held VARCHAR(3) NOT NULL,
base_price DECIMAL(8,2) NOT NULL,
discount DECIMAL(8,2) NOT NULL,
fee_1_surcharge DECIMAL(6,2) NOT NULL,
fee_2_6_pct_net_sales BIT NOT NULL,
fee_3 DECIMAL(5,2) NOT NULL,
tax_rate VARCHAR(6) NOT NULL,
tax_1_city BIT NOT NULL,
tax_2_pst BIT NOT NULL,
tax_3_gst DECIMAL(6,2) NOT NULL,
total_cost DECIMAL(8,2) NOT NULL,
performance_notes VARCHAR(1000) NULL,
venue_id VARCHAR(2) NOT NULL,
venue_name_internal VARCHAR(46) NOT NULL,
performance_pricing_map_id VARCHAR(2) NOT NULL,
pricing_map_name VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT GETDATE()
    );
    