
    CREATE TABLE staging.export_pass_data (
    patron_id VARCHAR(5) NOT NULL,
first_name VARCHAR(12) NULL,
last_name VARCHAR(12) NULL,
company VARCHAR(38) NULL,
pass_type_id VARCHAR(2) NOT NULL,
pass_description VARCHAR(36) NOT NULL,
pass_id VARCHAR(3) NOT NULL,
redemption_type VARCHAR(14) NOT NULL,
pass_year_fiscal VARCHAR(4) NOT NULL,
corporate BIT NOT NULL,
start_date VARCHAR(10) NOT NULL,
purchase_amount DECIMAL(6,2) NOT NULL,
tax_rate VARCHAR(6) NOT NULL,
tax_1_city BIT NOT NULL,
tax_2_pst BIT NOT NULL,
tax_3_gst BIT NOT NULL,
total_amount DECIMAL(6,2) NOT NULL,
control_id VARCHAR(10) NOT NULL,
online_redemption_code VARCHAR(15) NOT NULL,
issued_qty VARCHAR(2) NOT NULL,
issued_amount DECIMAL(6,2) NOT NULL,
used_qty VARCHAR(1) NOT NULL,
used_amount DECIMAL(4,1) NOT NULL,
redeemed_qty BIT NOT NULL,
redeemed_amount BIT NOT NULL,
remain_qty VARCHAR(2) NOT NULL,
remain_amount DECIMAL(5,2) NOT NULL,
expiry_date VARCHAR(10) NULL,
date_full_redemption VARCHAR(10) NULL,
pass_notes VARCHAR(255) NULL,
order_id VARCHAR(6) NOT NULL,
created_at DATETIME DEFAULT GETDATE()
    );
    