
    CREATE TABLE staging.export_tickets (
    patron_id VARCHAR(5) NOT NULL,
first_name VARCHAR(20) NULL,
last_name VARCHAR(21) NULL,
company VARCHAR(255) NULL,
ticket_id VARCHAR(6) NOT NULL,
event_id VARCHAR(4) NOT NULL,
event VARCHAR(255) NOT NULL,
event_code VARCHAR(6) NOT NULL,
performance_id VARCHAR(4) NOT NULL,
performance_code VARCHAR(8) NOT NULL,
performance_date VARCHAR(19) NOT NULL,
quantity BIT NOT NULL,
price_code VARCHAR(1) NOT NULL,
price_description VARCHAR(20) NULL,
section_row_seat VARCHAR(14) NULL,
base_price DECIMAL(5,2) NOT NULL,
discount DECIMAL(5,2) NOT NULL,
fee_1_surcharge DECIMAL(3,2) NOT NULL,
fee_2_6_pct_net_sales BIT NOT NULL,
fee_3 DECIMAL(4,2) NOT NULL,
tax_rate VARCHAR(6) NOT NULL,
tax_1_city BIT NOT NULL,
tax_2_pst BIT NOT NULL,
tax_3_gst DECIMAL(4,2) NOT NULL,
total_cost DECIMAL(5,2) NOT NULL,
sales_promotion_id VARCHAR(4) NOT NULL,
sales_promotion VARCHAR(40) NOT NULL,
date_bought VARCHAR(19) NOT NULL,
ticket_date_printed VARCHAR(19) NULL,
ticket_date_scanned VARCHAR(19) NULL,
patron_attended_flag BIT NOT NULL,
redeemed_by_pass INT NULL,
patron_intended_for VARCHAR(5) NOT NULL,
first_name_2 VARCHAR(15) NULL,
first_last_2 VARCHAR(14) NULL,
company_2 VARCHAR(38) NULL,
order_id VARCHAR(6) NOT NULL,
created_at DATETIME DEFAULT GETDATE()
    );
    