
    CREATE TABLE staging.export_mail_list_data_full (
    id INT IDENTITY(1,1) PRIMARY KEY,
mail_list_id VARCHAR(3) NOT NULL,
mail_list_name VARCHAR(47) NOT NULL,
patron_id VARCHAR(5) NOT NULL,
patron_type VARCHAR(23) NOT NULL,
salutation VARCHAR(11) NULL,
first_name VARCHAR(31) NULL,
initial VARCHAR(20) NULL,
last_name VARCHAR(21) NULL,
suffix VARCHAR(50) NULL,
greeting VARCHAR(20) NULL,
formal_name VARCHAR(44) NULL,
company VARCHAR(255) NULL,
title VARCHAR(29) NULL,
deceased BIT NOT NULL,
address_line_1 VARCHAR(50) NULL,
address_line_2 VARCHAR(30) NULL,
city VARCHAR(21) NULL,
province VARCHAR(11) NULL,
postal_code VARCHAR(10) NULL,
country VARCHAR(8) NOT NULL,
primary_phone VARCHAR(23) NULL,
primary_email VARCHAR(47) NULL,
do_not_mail_patron BIT NOT NULL,
do_not_mail_venue BIT NOT NULL,
do_not_email BIT NOT NULL,
do_not_telemarket BIT NOT NULL,
do_not_trade BIT NOT NULL,
do_not_solicit_email BIT NOT NULL,
do_not_solicit_mail BIT NOT NULL,
do_not_solicit_phone BIT NOT NULL,
created_at DATETIME DEFAULT GETDATE()
    );
    